// This lock polyfill has been borrowed from the SimonCropp's excellent Polyfill project
// Original Implementation: https://github.com/SimonCropp/Polyfill/blob/49ebfe4ee1ce10b4872b83d4c5fdb53b9c808f4f/src/Polyfill/Lock.cs

// Copyright (c) Simon Cropp
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.


// <auto-generated />
#pragma warning disable

#nullable enable

#if !NET9_0_OR_GREATER

namespace System.Threading;

using Diagnostics;
using Diagnostics.CodeAnalysis;
using Link = ComponentModel.DescriptionAttribute;

/// <summary>
/// Provides a way to get mutual exclusion in regions of code between different threads. A lock may be held by one thread at
/// a time.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
//Link: https://learn.microsoft.com/en-us/dotnet/api/system.threading.lock
public class Lock
{
#if NETCOREAPP || NETFRAMEWORK || NETSTANDARD
    public bool IsHeldByCurrentThread => Monitor.IsEntered(this);
#endif

    /// <summary>
    /// Enters the lock. Once the method returns, the calling thread would be the only thread that holds the lock.
    /// </summary>
    public void Enter() => Monitor.Enter(this);

    /// <summary>
    /// Tries to enter the lock without waiting. If the lock is entered, the calling thread would be the only thread that
    /// holds the lock.
    /// </summary>
    /// <returns>
    /// <code>true</code> if the lock was entered, <code>false</code> otherwise.
    /// </returns>
    public bool TryEnter() => Monitor.TryEnter(this);

    /// <summary>
    /// Tries to enter the lock, waiting for roughly the specified duration. If the lock is entered, the calling thread
    /// would be the only thread that holds the lock.
    /// </summary>
    /// <param name="timeout">
    /// The rough duration for which the method will wait if the lock is not available. The timeout is converted to a number
    /// of milliseconds by casting <see cref="TimeSpan.TotalMilliseconds"/> of the timeout to an integer value. A value
    /// representing <code>0</code> milliseconds specifies that the method should not wait, and a value representing
    /// <see cref="Timeout.Infinite"/> or <code>-1</code> milliseconds specifies that the method should wait indefinitely
    /// until the lock is entered.
    /// </param>
    /// <returns>
    /// <code>true</code> if the lock was entered, <code>false</code> otherwise.
    /// </returns>
    public bool TryEnter(TimeSpan timeout) =>
        Monitor.TryEnter(this, timeout);

    /// <summary>
    /// Tries to enter the lock, waiting for roughly the specified duration. If the lock is entered, the calling thread
    /// would be the only thread that holds the lock.
    /// </summary>
    /// <param name="millisecondsTimeout">
    /// The rough duration in milliseconds for which the method will wait if the lock is not available. A value of
    /// <code>0</code> specifies that the method should not wait, and a value of <see cref="Timeout.Infinite"/> or
    /// <code>-1</code> specifies that the method should wait indefinitely until the lock is entered.
    /// </param>
    /// <returns>
    /// <code>true</code> if the lock was entered, <code>false</code> otherwise.
    /// </returns>
    public bool TryEnter(int millisecondsTimeout) =>
        TryEnter(TimeSpan.FromMilliseconds(millisecondsTimeout));

    /// <summary>
    /// Exits the lock.
    /// </summary>
    public void Exit() => Monitor.Exit(this);

    /// <summary>
    /// Enters the lock and returns a <see cref="Scope"/> that may be disposed to exit the lock. Once the method returns,
    /// the calling thread would be the only thread that holds the lock. This method is intended to be used along with a
    /// language construct that would automatically dispose the <see cref="Scope"/>, such as with the C# <code>using</code>
    /// statement.
    /// </summary>
    /// <returns>
    /// A <see cref="Scope"/> that may be disposed to exit the lock.
    /// </returns>
    public Scope EnterScope()
    {
        Enter();
        return new Scope(this);
    }

    /// <summary>
    /// A disposable structure that is returned by <see cref="EnterScope()"/>, which when disposed, exits the lock.
    /// </summary>
    public readonly ref struct Scope(Lock owner)
    {
        /// <summary>
        /// Exits the lock.
        /// </summary>
        public void Dispose() => owner.Exit();
    }
}

#else
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Threading.Lock))]
#endif
